apiVersion: v1
kind: PersistentVolume
metadata:
  name: audit-service-mysql-pv-claim
  namespace: dev-audit    
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: audit-service-mysql-pv-claim-dev
    namespace: dev-audit
  hostPath:
    path: /tmp/hostpath-provisioner/dev-audit/audit-service-mysql-pv-claim
    type: ""
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  volumeMode: Filesystem
